version: '3'

services:
  postgres:
    image: card-brand-postgres-image
    container_name: card-brand-postgres-container
    build:
        context: ./ # Specify the path to your API project
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: BDCardBrand
      POSTGRES_USER: ojimenez
      POSTGRES_PASSWORD: ojimenez.
  myapi:
    image: card-brand-api-image
    container_name: card-brand-api-container
    build:
        context: . 
        dockerfile: CardBrand.Api/Dockerfile # Specify the path to your API project
    ports:
        - "5000:80"
    depends_on:
        - postgres